//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CONTRASTEntities : DbContext
    {
        public CONTRASTEntities()
            : base("name=CONTRASTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_m_arrange_cashallowance> tb_m_arrange_cashallowance { get; set; }
        public virtual DbSet<tb_m_destination> tb_m_destination { get; set; }
        public virtual DbSet<tb_m_divison_mapping> tb_m_divison_mapping { get; set; }
        public virtual DbSet<tb_m_employee> tb_m_employee { get; set; }
        public virtual DbSet<tb_m_lt_employee> tb_m_lt_employee { get; set; }
        public virtual DbSet<tb_m_lt_spec_employee> tb_m_lt_spec_employee { get; set; }
        public virtual DbSet<tb_m_overseas_allowance> tb_m_overseas_allowance { get; set; }
        public virtual DbSet<tb_m_overseas_flag> tb_m_overseas_flag { get; set; }
        public virtual DbSet<tb_m_participant_flag> tb_m_participant_flag { get; set; }
        public virtual DbSet<tb_m_rate_flight> tb_m_rate_flight { get; set; }
        public virtual DbSet<tb_m_rate_hotel> tb_m_rate_hotel { get; set; }
        public virtual DbSet<tb_m_rate_visa> tb_m_rate_visa { get; set; }
        public virtual DbSet<tb_m_region> tb_m_region { get; set; }
        public virtual DbSet<tb_m_request_type> tb_m_request_type { get; set; }
        public virtual DbSet<tb_r_photo_uploader_TEST> tb_r_photo_uploader_TEST { get; set; }
        public virtual DbSet<tb_r_travel_payment_verification> tb_r_travel_payment_verification { get; set; }
        public virtual DbSet<tb_r_travel_request_participant> tb_r_travel_request_participant { get; set; }
        public virtual DbSet<tb_m_budget> tb_m_budget { get; set; }
        public virtual DbSet<tb_m_dummy_div_mapping> tb_m_dummy_div_mapping { get; set; }
        public virtual DbSet<tb_m_mapping_approval> tb_m_mapping_approval { get; set; }
        public virtual DbSet<tb_m_mstr_user> tb_m_mstr_user { get; set; }
        public virtual DbSet<tb_m_photo_employee> tb_m_photo_employee { get; set; }
        public virtual DbSet<tb_m_spec_emp> tb_m_spec_emp { get; set; }
        public virtual DbSet<tb_r_travel_execution> tb_r_travel_execution { get; set; }
        public virtual DbSet<tb_r_travel_fixedcost_allowance> tb_r_travel_fixedcost_allowance { get; set; }
        public virtual DbSet<tb_r_travel_spec_employee> tb_r_travel_spec_employee { get; set; }
        public virtual DbSet<vw_lt_performance> vw_lt_performance { get; set; }
        public virtual DbSet<vw_travel_cost> vw_travel_cost { get; set; }
        public virtual DbSet<vw_travel_profile> vw_travel_profile { get; set; }
        public virtual DbSet<tb_r_travel_actualcost> tb_r_travel_actualcost { get; set; }
        public virtual DbSet<tb_r_travel_dit> tb_r_travel_dit { get; set; }
        public virtual DbSet<tb_r_travel_settlement> tb_r_travel_settlement { get; set; }
        public virtual DbSet<tb_m_travel_procedures> tb_m_travel_procedures { get; set; }
        public virtual DbSet<vw_travel_allowance> vw_travel_allowance { get; set; }
        public virtual DbSet<tb_r_travel_request> tb_r_travel_request { get; set; }
        public virtual DbSet<vw_request_summary> vw_request_summary { get; set; }
    
        [DbFunction("CONTRASTEntities", "fn_approval_update")]
        public virtual IQueryable<fn_approval_update_Result> fn_approval_update(string usr, string group)
        {
            var usrParameter = usr != null ?
                new ObjectParameter("usr", usr) :
                new ObjectParameter("usr", typeof(string));
    
            var groupParameter = group != null ?
                new ObjectParameter("group", group) :
                new ObjectParameter("group", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_approval_update_Result>("[CONTRASTEntities].[fn_approval_update](@usr, @group)", usrParameter, groupParameter);
        }
    
        [DbFunction("CONTRASTEntities", "fn_tr_apprvlist_1st")]
        public virtual IQueryable<fn_tr_apprvlist_1st_Result> fn_tr_apprvlist_1st(string usr)
        {
            var usrParameter = usr != null ?
                new ObjectParameter("usr", usr) :
                new ObjectParameter("usr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_tr_apprvlist_1st_Result>("[CONTRASTEntities].[fn_tr_apprvlist_1st](@usr)", usrParameter);
        }
    
        [DbFunction("CONTRASTEntities", "fn_tr_apprvlist_2nd")]
        public virtual IQueryable<fn_tr_apprvlist_2nd_Result> fn_tr_apprvlist_2nd(string usr)
        {
            var usrParameter = usr != null ?
                new ObjectParameter("usr", usr) :
                new ObjectParameter("usr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_tr_apprvlist_2nd_Result>("[CONTRASTEntities].[fn_tr_apprvlist_2nd](@usr)", usrParameter);
        }
    
        [DbFunction("CONTRASTEntities", "fn_tr_group_participant")]
        public virtual IQueryable<fn_tr_group_participant_Result> fn_tr_group_participant(string usr)
        {
            var usrParameter = usr != null ?
                new ObjectParameter("usr", usr) :
                new ObjectParameter("usr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_tr_group_participant_Result>("[CONTRASTEntities].[fn_tr_group_participant](@usr)", usrParameter);
        }
    
        [DbFunction("CONTRASTEntities", "fn_tr_groupcode_execution")]
        public virtual IQueryable<fn_tr_groupcode_execution_Result> fn_tr_groupcode_execution(string usr)
        {
            var usrParameter = usr != null ?
                new ObjectParameter("usr", usr) :
                new ObjectParameter("usr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_tr_groupcode_execution_Result>("[CONTRASTEntities].[fn_tr_groupcode_execution](@usr)", usrParameter);
        }
    
        [DbFunction("CONTRASTEntities", "fn_tr_photo_uploaderlist")]
        public virtual IQueryable<fn_tr_photo_uploaderlist_Result> fn_tr_photo_uploaderlist(string usr)
        {
            var usrParameter = usr != null ?
                new ObjectParameter("usr", usr) :
                new ObjectParameter("usr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_tr_photo_uploaderlist_Result>("[CONTRASTEntities].[fn_tr_photo_uploaderlist](@usr)", usrParameter);
        }
    
        public virtual int sp_approvalUpdate(string usr, string group, string status)
        {
            var usrParameter = usr != null ?
                new ObjectParameter("usr", usr) :
                new ObjectParameter("usr", typeof(string));
    
            var groupParameter = group != null ?
                new ObjectParameter("group", group) :
                new ObjectParameter("group", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_approvalUpdate", usrParameter, groupParameter, statusParameter);
        }
    
        public virtual int sp_participantUpdate(string usr, string group, Nullable<int> noreg_participant, string status_travel, Nullable<int> status_participant)
        {
            var usrParameter = usr != null ?
                new ObjectParameter("usr", usr) :
                new ObjectParameter("usr", typeof(string));
    
            var groupParameter = group != null ?
                new ObjectParameter("group", group) :
                new ObjectParameter("group", typeof(string));
    
            var noreg_participantParameter = noreg_participant.HasValue ?
                new ObjectParameter("noreg_participant", noreg_participant) :
                new ObjectParameter("noreg_participant", typeof(int));
    
            var status_travelParameter = status_travel != null ?
                new ObjectParameter("status_travel", status_travel) :
                new ObjectParameter("status_travel", typeof(string));
    
            var status_participantParameter = status_participant.HasValue ?
                new ObjectParameter("status_participant", status_participant) :
                new ObjectParameter("status_participant", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_participantUpdate", usrParameter, groupParameter, noreg_participantParameter, status_travelParameter, status_participantParameter);
        }
    
        public virtual int sp_rejectUpdate(string usr, string group, string status, string comments)
        {
            var usrParameter = usr != null ?
                new ObjectParameter("usr", usr) :
                new ObjectParameter("usr", typeof(string));
    
            var groupParameter = group != null ?
                new ObjectParameter("group", group) :
                new ObjectParameter("group", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var commentsParameter = comments != null ?
                new ObjectParameter("comments", comments) :
                new ObjectParameter("comments", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_rejectUpdate", usrParameter, groupParameter, statusParameter, commentsParameter);
        }
    
        public virtual int sp_update_approver(Nullable<int> no_reg, Nullable<bool> overseas, Nullable<System.DateTime> date)
        {
            var no_regParameter = no_reg.HasValue ?
                new ObjectParameter("no_reg", no_reg) :
                new ObjectParameter("no_reg", typeof(int));
    
            var overseasParameter = overseas.HasValue ?
                new ObjectParameter("overseas", overseas) :
                new ObjectParameter("overseas", typeof(bool));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_update_approver", no_regParameter, overseasParameter, dateParameter);
        }
    }
}
