//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_m_spec_emp
    {
        public int id_spec_emp { get; set; }
        public string no_reg { get; set; }
        public string name { get; set; }
        public string apprv_dh_1 { get; set; }
        public string apprv_dh_2 { get; set; }
        public string apprv_dh_3 { get; set; }
        public string apprv_egm_1 { get; set; }
        public string apprv_egm_2 { get; set; }
        public string apprv_dir_1 { get; set; }
        public string apprv_dir_2 { get; set; }
        public string apprv_dir_3 { get; set; }
        public string apprv_dir_vp { get; set; }
        public string apprv_dir_pd { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<bool> active { get; set; }
    }
}
