//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_r_photo_uploader_TEST
    {
        public int id_uploader { get; set; }
        public int id_request { get; set; }
        public string path_upload { get; set; }
        public string desc_upload { get; set; }
        public Nullable<int> uploaded { get; set; }
        public Nullable<int> numbers { get; set; }
        public string user_created { get; set; }
        public Nullable<System.DateTime> insert_date { get; set; }
    }
}
