//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_r_travel_spec_employee
    {
        public int id_exep_employee { get; set; }
        public Nullable<int> id_request { get; set; }
        public Nullable<int> no_reg_assignment { get; set; }
        public Nullable<System.DateTime> assigment_date { get; set; }
        public Nullable<int> apprv_dh1 { get; set; }
        public Nullable<int> apprv_dh2 { get; set; }
        public Nullable<int> apprv_dh3 { get; set; }
        public Nullable<int> apprv_egm1 { get; set; }
        public Nullable<int> apprv_egm2 { get; set; }
        public Nullable<int> apprv_dir1 { get; set; }
        public Nullable<int> apprv_dir2 { get; set; }
        public Nullable<int> apprv_dir3 { get; set; }
        public Nullable<int> apprv_dir_vp { get; set; }
        public Nullable<int> apprv_dir_pd { get; set; }
        public string apprv_flag_dh1 { get; set; }
        public string apprv_flag_dh2 { get; set; }
        public string apprv_flag_dh3 { get; set; }
        public string apprv_flag_egm1 { get; set; }
        public string apprv_flag_egm2 { get; set; }
        public string apprv_flag_dir1 { get; set; }
        public string apprv_flag_dir2 { get; set; }
        public string apprv_flag_dir3 { get; set; }
        public string apprv_flag_dir_vp { get; set; }
        public string apprv_flag_dir_pd { get; set; }
        public Nullable<System.DateTime> apprv_date_dh1 { get; set; }
        public Nullable<System.DateTime> apprv_date_dh2 { get; set; }
        public Nullable<System.DateTime> apprv_date_dh3 { get; set; }
        public Nullable<System.DateTime> apprv_date_egm1 { get; set; }
        public Nullable<System.DateTime> apprv_date_egm2 { get; set; }
        public Nullable<System.DateTime> apprv_date_dir1 { get; set; }
        public Nullable<System.DateTime> apprv_date_dir2 { get; set; }
        public Nullable<System.DateTime> apprv_date_dir3 { get; set; }
        public Nullable<System.DateTime> apprv_date_dir_vp { get; set; }
        public Nullable<System.DateTime> apprv_date_dir_pd { get; set; }
        public string user_created { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    }
}
