//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_travel_profile
    {
        public int id_request { get; set; }
        public Nullable<int> no_reg { get; set; }
        public Nullable<int> destination_code { get; set; }
        public Nullable<bool> overseas_flag { get; set; }
        public Nullable<int> id_travel_type { get; set; }
        public Nullable<bool> request_type { get; set; }
        public string travel_purpose { get; set; }
        public Nullable<bool> air_ticket_flag { get; set; }
        public Nullable<bool> passport_flag { get; set; }
        public Nullable<int> apprv_by_lvl1 { get; set; }
        public Nullable<int> apprv_by_lvl2 { get; set; }
        public Nullable<int> apprv_by_lvl3 { get; set; }
        public Nullable<int> apprv_by_lvl4 { get; set; }
        public Nullable<int> apprv_by_lvl5 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl1 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl2 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl3 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl4 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl5 { get; set; }
        public Nullable<double> budget { get; set; }
        public Nullable<bool> exep_empolyee { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> duration { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string comments { get; set; }
        public Nullable<double> transit_by_land { get; set; }
        public Nullable<double> transit_by_air { get; set; }
        public Nullable<double> total_transit { get; set; }
        public Nullable<double> allowance_transit_by_land { get; set; }
        public Nullable<double> allowance_transit_by_air { get; set; }
        public Nullable<double> total_allowance_transit { get; set; }
        public Nullable<double> allowance_meal_idr { get; set; }
        public Nullable<double> allowance_meal_jpy { get; set; }
        public Nullable<double> allowance_meal_usd { get; set; }
        public Nullable<double> allowance_hotel { get; set; }
        public Nullable<double> allowance_transportation { get; set; }
        public Nullable<double> allowance_laundry { get; set; }
        public Nullable<double> allowance_miscellaneous { get; set; }
        public Nullable<double> total_allowance_basic { get; set; }
        public Nullable<double> allowance_ticket { get; set; }
        public Nullable<double> allowance_visa { get; set; }
        public Nullable<double> allowance_passport { get; set; }
        public Nullable<double> total_allowance_document { get; set; }
        public Nullable<double> grand_total_allowance { get; set; }
        public Nullable<bool> active_flag { get; set; }
    }
}
